services:
  mongodb:
    image: mongo:7.0
    container_name: cultural-vault-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cultural_vault
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cultural-vault-network

  app:
    build: .
    container_name: cultural-vault-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=cultural_vault
    depends_on:
      - mongodb
    networks:
      - cultural-vault-network

  ai-service:
    build: ./ai-service
    container_name: cultural-vault-ai
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service/models:/app/models
    networks:
      - cultural-vault-network

volumes:
  mongodb_data:

networks:
  cultural-vault-network:
    driver: bridge
