spring:
  application:
    name: CulturalVault
  
  # MongoDB Configuration - FIXED: Added spring: prefix
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cultural_vault}
  
  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # disable in development
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Custom Application Properties
app:
  jwt:
    secret: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEN1bHR1cmFsVmF1bHQ=
    expiration: 3600
  
  # Cloudflare R2 Configuration
  storage:
    r2:
      access-key-id: ${R2_ACCESS_KEY_ID:}
      secret-access-key: ${R2_SECRET_ACCESS_KEY:}
      bucket-name: cultural-vault-artifacts
      endpoint: ${R2_ENDPOINT:}  # FIXED: Was R2_ENPOINT
      region: auto
  
  # AI Service Configuration
  ai:
    service:
      base-url: http://localhost:5000
      timeout: 30000  # FIXED: 30 seconds, not 3
  
  # External APIs
  api:
    europeana:
      base-url: https://api.europeana.eu/record/v2
      api-key: ${EUROPEANA_API_KEY:}
      rate-limit: 10000
    
    smithsonian:  # FIXED: Was "simthsonian"
      base-url: https://api.si.edu/openaccess/api/v1.0
      rate-limit: 1000

# Logging Configuration - FIXED: Package name
logging:
  level:
    com.culturalvault: DEBUG  # FIXED: Was com.culturevault
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: INFO  # Reduced verbosity
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/cultural-vault.log  # FIXED: Was culture-vault.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized